### ISSUE TITLE
To-Do: Weekly Goals

### ISSUE THREAD

**Issue by MathewGolding** [Waztom/xchem-CAR#84]
- [ ] Get a copy of mestrenova
- [ ] - [ ] Finish Batch 3 analysis
- [ ] Prepare LCMS experiments
- [ ] Revise ANOVA and t-tests (small break on DoE for now)
- [ ] Begin mapping out specifications for car API and Chem Inventory systems

**Comment by Waztom** [comment]
@MathewGolding is the action not rather testing Excel/bar code scanner for tracking compound/logistics?

**Comment by MathewGolding** [comment]
I will add that on there now.

**Comment by MathewGolding** [comment]
25/01/24

- [ ] Begin analysis of LCMS data - (reactants and products, RRF values)
- [ ] Clean OT - canned air clean the track/rail
- [ ] Test Dry run/Wet run of 96 start mat vials - not urgent but to do
- [ ] Buy BB from the eyeballing of compounds recently done
- [ ] Car uploads
- [ ]  Test bar code method scanning methodology with upcoming 2A run (overarking goal)
- [ ]  Get one windows "diamonised" machine in the RCaH - may go on for over 1 week
- [ ] Create project swim lanes!

**Comment by MathewGolding** [comment]
29/01/24

- [ ] Look in cheminv to check whether the ring I liked exists on compounds we presently have
- [ ] Begin constructing slides for presentation - NCS1 and CAR Development
- [ ] Sort ChemInv
- [ ] Finish conversion analysis via lcms of the 14 sample set
- [ ] Check for and prepopulate probation period documentation
- [ ] Create ticket for CAS Number to SMILES search with PubChemPy
- [ ] Create project to do list tickets

**Comment by MathewGolding** [comment]
## 12/02/24
### Science
- [ ] Review talk outline in powerpoint for presentation, figures, etc
- [ ] Do paladium catalyst - solvent tests n.b. get Tom Webb's data (message today (12/02/24))
- [ ] Redo LCMS of starting materials in one LCMS plate well (create mixture) - compare rrf value of at least one
- [ ] Do test reactions on small scale suzuki test reactions to get used to them -> start with suz-2 4x4 combichem (analysis can also be done to do lcms for mscheck analysis)
### Lab operations
- [ ] Create a cheminv catalogue ticket -> better organise the many tasks chem inventory needs doing (move old assignments to new - create physical and data names for the cabinets)
- [ ] Get label maker working for the physical labels
- [ ] Fill out waste disposal forms and clear out waste cabinet
- [ ] Organise the "trolley" - select whether keep/disgard items
- [ ] Dry and then wet run of 96 reactant vials
- [ ] Update LCMS and CAR SOPs
- [ ] Create confluence page for ChemInv and other documentation
### Admin
- [ ] Create project to do lists to separate project goals and view them more succinctly
- [ ] Check pubchem api methods for Cas number -> smiles searching
- [ ] Order 96 well filtration plates - need quote from Biotage -> hasn't replied yet

**Comment by MathewGolding** [comment]
## 26/02/24
### Science
- [ ] Review talk outline in powerpoint for presentation, figures, etc
- [ ] <s> Do paladium catalyst - solvent tests n.b. get Tom Webb's data (message today (12/02/24)) </s> Don't have enough catalyst to reasonably do this for suzuki. Keep in mind for Buchwal-Hartwig. -> Research literature for the solubility of these catalysts.
### Lab operations
- [x] Waste cabinet organisation - NOTE: get caps for bottles
- [x] Organise the "trolley" - NOTE: select whether keep/disgard items - go through after meeting
- [x] Update LCMS and CAR SOPs - NOTE: Update encoded recipe SOP
- [ ] Create confluence page for ChemInv and other documentation
### Admin


- [ ] Create project to do lists to separate project goals and view them more succinctly:
> - [x] Create project tickets
> - [ ] Populate the tickets
- [ ] Check pubchem api methods for Cas number -> smiles searching

**Comment by MathewGolding** [comment]
## 08/04/24
### Science
- [ ] Wasgo iter-1 two step reactions - review CAR recipes and plan and prepare to execute the chemistry to execute on CAR.
- [ ] Hand over plate XC-EVA712A-wasgo-iter-1.0-2 to Ryan for soaking
- [ ] Wasgo iter-2 - review compounds ordered and plan chemistry to execute on CAR for iter-2 compounds.
- [ ] Reaction methods development - plan a suitable set of reaction that would prove the effectiveness of "print-press" reactions in a HTE format.
- [ ] MSCheck Development - review the two different conversion estimations and flesh out and define an input/output excel sheet for development
### Lab Operations
- [ ] Contact Charlie on how to create a confluence page of ChemInv - needs a ticket to itself
- [ ] Finalise SOP on lab maintance
- [ ] Weekly lab check
### Admin
- [ ] Scarab (High Priority) see #93 for futher details
- [ ] Contact starlab - 96 tip rack for 200uL xl tips exist
- [ ] Prepopulate 6 month probation form
- [ ] Meeting 15th Apr

**Comment by MathewGolding** [comment]
## 22/04/24
### Science
- [ ] Perform LCMS analysis on Batch 1 of the two step iter 1.0 wasgo compounds
- [ ] Begin preperation and execute synthesis of Batch 2 of the two step iter 1.0 wasgo compounds
- [ ] Wasgo iter-2 - review compounds ordered and plan chemistry to execute on CAR for iter-2 compounds - tbd next week
- [ ] Get press to lab - speak to Mic (beamline engineer)
- [ ] Plan a suitable set of reaction that would prove the effectiveness of "print-press" reactions in a HTE format - ticket - next week
### Lab Operations
- [ ] Switch LCMS back on post installation (Tuesday)
- [ ] Review and finalise wording of lab maintanance SOP checklist
### Admin
- [ ]  Contact starlab - 96 tip rack for 200uL xl tips
- [ ] Prepopulate 6 month probation form -> find out from HR if I need to do a performance development review (email and copy warren in)

**Comment by MathewGolding** [comment]
## 29/04/24
### Science
- [ ] Prepare 0.1 mM standard and run LCMS for wasgo iter 1.1 batch 1 (high priority - today)
- [ ] analyse batch 1 via MSCheck and manual review to gain conversion estimates
- [ ] Wasgo iter-2 - review compounds ordered and plan chemistry to execute on CAR for iter-2 compounds - tbd next week?
- [ ] Get press to lab - speak to Mic (beamline engineer) - tbd next week?
- [ ] Plan a suitable set of reaction that would prove the effectiveness of "print-press" reactions in a HTE format - ticket - tbd next week?
### Lab operations

- [ ] Begin fridge/freezer clean up?
- [ ] Review CAR 384 plates 100 uL labcyte echo set up

### Admin
- [ ] Reword probation form and prepopulate PDR

**Comment by MathewGolding** [comment]
## 08/05/24
### Science
- [ ] Prepare 0.1 mM standard and run LCMS for wasgo iter 1.1 batch 1 (high priority - today)
- [ ] analyse batch 1 via MSCheck and manual review to gain conversion estimates
- [ ] _Get press to lab - speak to Mic (beamline engineer) - tbd next week?_
- [ ] _Plan a suitable set of reaction that would prove the effectiveness of "print-press" reactions in a HTE format - ticket - tbd next week?_ 
- [ ] _Wasgo iter-2 - review compounds ordered and plan chemistry to execute on CAR for iter-2 compounds - tbd next week?_
### Lab operations

- [ ] Begin fridge/freezer clean up?
- [x] Review CAR 384 plates 100 uL labcyte echo set up

### Admin
- [ ] Reword probation form and prepopulate PDR

**Comment by MathewGolding** [comment]
## 28/05/24
### Science
- [ ] analyse iter 1.0 and iter 1.1 batch 2 via MSCheck excel template to gain conversion estimates (~100)
- [ ] Get Lab PC and network this PC to diamond (@Waztom)
- [ ] _Get press to lab - speak to Mic (beamline engineer) - tbd next week?_
- [ ] _Plan a suitable set of reaction that would prove the effectiveness of "print-press" reactions in a HTE format - ticket - tbd next week?_ 
- [ ] _Wasgo iter-2 - review compounds ordered and plan chemistry to execute on CAR for iter-2 compounds - tbd next week?_
### Lab operations

- [ ] Begin fridge/freezer clean up
- [ ] Begin Lab clean up -> see action list in emails from Warren

### Admin
- [ ] Refine Scarab entries and input Scarab of Wasgo iter 1.0 and 1.1 to high quality level
